# https://www.home-assistant.io/integrations/default_config/
default_config:

# auto_areas:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.auto_areas: debug
